readinessProbe:
    enabled: true
    path: /v1/sys/health?standbyok=true
    port: 8200
    failureThreshold: 2
    initialDelaySeconds: 120
    periodSeconds: 300
    successThreshold: 1
    timeoutSeconds: 120
# Used to enable a livenessProbe for the pods
livenessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true"
    port: 8200
    failureThreshold: 2
    initialDelaySeconds: 120
    periodSeconds: 300
    successThreshold: 1
    timeoutSeconds: 120